HAI 1.2
VISIBLE "PRINT ME 1"
VISIBLE ALL OF 9 AN FAIL AN FAIL AN WIN
VISIBLE PRODUKT OF 9.123 AN 9
VISIBLE "PRINT ME 2"
VISIBLE SMOOSH "HELLO" AN "WORLD" AN "!"
VISIBLE BOTH SAEM 8 AN 8
VISIBLE WIN
KTHXBYE